### ISSUE TITLE
Control number of frets?

### ISSUE THREAD

**Issue by MilesMorel** [calinalexandru/chord-illustrator-js#1]
Nice work! Looks really clean. So I don't see an option to set the number of frets. I think setting the number of frets is essential for this module to be useable. Many guitar chords span more than 3 frets and at more frets it would make for nice scale diagrams and maybe even a fretboard too. Please let me know if you plan to add this or if I missed something. Happy to help if needed.

**Comment by calinalexandru** [comment]
Hello,
Currently there is no support for increasing the number of frets - it will be developed in the near future and I will update  README.md accordingly

**Comment by MilesMorel** [comment]
Sweet thanks!

**Comment by calinalexandru** [comment]
Hello,
The fretboard now expands automatically based on min/max fret. I thought this would make more sense, rather than specifying the fretboard size - If you make a good case thought, i can add the fretboard size as a parameter :)
If you cloned this repo you can run "npm run test", which will create **./static/** folder filled with chord goodies.

**Comment by MilesMorel** [comment]
Sweet thanks!

**Comment by MilesMorel** [comment]
I finally got a chance to check it out. It looks as though the fretboard now spans from the open fret to the max fret in the chord. It seems to always show all the way down to the open frets though, which isn't always desirable (e.g. if you have a chord way up on the neck, for instance). I'm not sure if maybe I missed an option or something.

Is there any way you could expose a fretboardRange parameter (or equivalent) in the options object? That way the user would have optional control over what portion of the fretboard is shown. An example use case would be that it might be preferable to show down to the open frets if a chord uses frets 1-4, whereas if a chord uses frets 5-8, it would be preferable perhaps to start the fretboard at fret 4 for the sake of legibility. 

I've got it integrated into my site as a component but can't quite use it in production yet for this reason.

**Comment by calinalexandru** [comment]
Ok, I will start working on a fretboardRange parameter, for the case you've made or yet unforeseen cases.
sorry for the delayed response, i managed to sprain my wrist last weekend >.<

**Comment by MilesMorel** [comment]
Hey thanks for taking that on, that's awesome! So sorry to hear about your wrist. What a nightmare for a programmer... Wishing you a fast and easy recovery and looking forward to trying it out.

**Comment by calinalexandru** [comment]
Hello,
Thanks for your kind words, my hand is back to speed now xD
I made the changes regarding the _fretboardRange_ request - inside the chord data object, you can specify eg: **fretboardRange: {start: 1, end: 12}** . Please tell me if it works for you or find any issues.

**Comment by MilesMorel** [comment]
Will try it in a couple days. Thanks so much!

**Comment by MilesMorel** [comment]
Nice, I was able to get it working, however the API did not work in an intuitive way to me. To render a fretboard from fret 8 to 12 I expected to use fretboardRange: {start: 8, end: 12}. Instead the way to do this was fretboardRange: {start: 8, end: 4}. It would appear that your "end" prop is actually more akin to "fretboardLength" or "numberOfFrets". In any case, this works for me so all good, just might want to update the docs if you don't change the API so the intention is clear.

**Comment by calinalexandru** [comment]
It seems that you're right, currently "end" behaves like fretboard length, however, I will attempt to fix this bug so it will reflect current API docs

**Comment by MilesMorel** [comment]
Hey just wanted to let you know that I started using your fretboard in production at my very young (2 person) start-up,  [Motifai](https://www.motifai.com). As a token of my appreciation, here is a beta pass: 6RMR-KZR2-KKY9-Y8TQ. We have a few bugs but it's coming together. Feel free to let me know what you think at contact@motifai.com and I'd also be happy to give many more passes for you and your guitar friends if you like. Wish we could do more now but maybe one day. Thanks again!

**Comment by calinalexandru** [comment]
Hello,
It looks awesome, it's simple and effective (got me practicing scales). I'll mail you a comprehensive feedback once i try out all the features. I'm gonna ask for 2 more beta pass for some of my guitar buddies, is that ok :D? Thanks! Best of luck in your endeavour!

**Comment by MilesMorel** [comment]
Thanks, really appreciate it! We have a few known bugs (8th notes or fast tempos on some devices are unreliable, for instance), but should be fixed in the next week. Hoping it can become a really useful tool and fun game for guitarists and eventually for all musicians. Here are 4 more passes. Happy shredding!

4DJJ-U42G-SVYP-7DYL
U1TP-47JE-BFDF-28NW
9W7V-ZTE2-NZUQ-AGQ2
Y37X-TU4U-T8WV-GHDG
