### ISSUE TITLE
fr# in svg text

### ISSUE THREAD

**Issue by MilesMorel** [calinalexandru/chord-illustrator-js#2]
Hi this is pretty minor and I can certainly hack around it if need be, but I think including "fr #", an unusual abbreviation for "fret" where a non-italicized number with no letters is the standard for fretboard diagrams, is likely to clash with most use-cases imho. The same is true of the name field in ci make options which I currently set to an empty string to avoid unwanted text from rendering that doesn't match my design. Maybe it would be nice to include a {labels: off} option? Otherwise, I think just writing the fret number (e.g. without italics and without "fr") would be more standard of fretboard diagrams.

**Comment by calinalexandru** [comment]
Hi,
I haven't given much thought to the labels - I did find some chord diagrams online from which I inspired the format, but definitely some way of customizing or turning off is required. I'll get to that soon.
